export const ACTIONS = {
  LOAD_TASKS: 'LOAD_TASKS',
  CREATE_TASK: 'CREATE_TASK',
  CREATE_TASK_FAILED: 'CREATE_TASK_FAILED',
  SET_UPDATE_TASK: 'SET_UPDATE_TASK',
  UPDATE_TASK: 'UPDATE_TASK',
  UPDATE_TASK_FAILED: 'UPDATE_TASK_FAILED',
  DELETE_TASK: 'DELETE_TASK',
};

export const MESSAGES = {
  CREATED_SUCCESS: 'Entity Created',
  UPDATED_SUCCESS: 'Entity Updated',
  DELETED_SUCCESS: 'Entity Deleted',
};
